### ISSUE TITLE
Antler Shield incorrect calculations

### ISSUE THREAD

**Issue by ii3eas7** [Wet-Boys/LookingGlass#114]
The description for Antler Shield states the item grants 55% (+5%) chance on being hit to reflect 10% (+10%) damage back to the attacker. The actual formula used to calculate reflection chance at the bottom appears to use a 50% base chance - instead of the aforementioned 55% - of reflecting damage.

**Comment by ToastedOven** [comment]
The calculations actually match how the code in the game functions. The description is just wrong. We grab descriptions from the logbook so that different languages don't have issues. (as opposed to manually writing the descriptions without translations) There are quite a few items like this in the new update. While technically we could fix the logbooks to be correct, I feel this might fall out of scope for LookingGlass. One could make a "logbook description fixer" mod and by nature of how LookingGlass works it would pick it up no problem. Realistically however, Gearbox should just write correct descriptions.

**Comment by ii3eas7** [comment]
Got it, appreciate the explanation.
