### ISSUE TITLE
text size config option suggestion

### ISSUE THREAD

**Issue by Phreelosu** [Wet-Boys/LookingGlass#15]
![image](https://github.com/Wet-Boys/LookingGlass/assets/97800476/39088bb9-fa8a-4493-b75f-81903bb31a20)

this is in simulacrum, and I still kinda feel like there should be an option for this to be resized or something
it can get off-screen during simulacrum and even more so in void fields when there is a new UI extension containing items and monsters for each wave

**Comment by ToastedOven** [comment]
I added a global option for text size, also keep in mind, since it is just TextMeshPro, you can do something like "<size=80%>MyTextHere</size\>" if you ever need more customization. However while testing this for the video, I noticed a funny issue with RoO that I forwarded to rune (the <> stuff just vanishing into the void)

https://github.com/Wet-Boys/LookingGlass/assets/49164897/ff857ae6-ec10-4c01-bb23-f05655e9daa1

 Looking to add a couple items to the StatsDisplay syntax tonight, I think I'll change "Not Applicable" to just "N/A" so it doesn't take up nearly as much space
